apps/detector/urls.py
from django.urls import path
from .views import MNISTIndexView, MnistPredictionView

app_name = 'detector'

urlpatterns = [
    path('', MNISTIndexView.as_view(), name='index'),
    path('get_mnist_predictions/', MnistPredictionView.as_view(), name='get_mnist_predictions')
]

mnist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.detector.urls'), name='detector')
]

apps/detector/models.py
from django.db import models

# Create your models here.

apps/detector/views.py
import base64
import re
from io import BytesIO

import numpy as np

import torch
import torch.nn.functional as F
from PIL import Image
from django.views.generic import TemplateView
from django.shortcuts import render
from rest_framework.parsers import JSONParser, MultiPartParser
from rest_framework.response import Response
from rest_framework.views import APIView

from .detector import mnist, mnist_transforms, device


# Create your views here.

class MNISTIndexView(TemplateView):
    template_name = 'detector/index.html'


class MnistPredictionView(APIView):
    parser_classes = [JSONParser, MultiPartParser]

    def post(self, request):
        image_data = request.POST.get('canvasImage')
        image_data = re.sub("^data:image/png;base64,", "", image_data)
        image_data = base64.b64decode(image_data)
        image_data = BytesIO(image_data)
        img = Image.open(image_data)

        img_arr = np.array(img)
        img_arr = img_arr[:, :, 3]

        img = Image.fromarray(img_arr)
        transformed_img = mnist_transforms(img)
        transformed_img.to(device)
        transformed_img = torch.unsqueeze(transformed_img, 0)

        out = mnist(transformed_img)
        out = F.softmax(out, dim=1)
        out = out.detach().tolist()
        data = [{'index': index, 'value': value} for index, value in enumerate(out[0])]

        return Response({'data': data})

apps/detector/templates/detector/index.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
    MNIST
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'detector/css/index.css' %}">
{% endblock %}

{% block main_content %}
    <div class="container my-5">
        <div class="p-5">
            <div id="app" @mouseup="bodyMouseUp" @mouseout="bodyMouseOut">
                <div class="card elevation">
                    <div class="row text-center mt-3">
                        <div class="col-md-12">
                            <canvas class="canvas elevation" id="canvas" @mousedown="canvasMouseDown"
                                    @mousemove="canvasMouseMove" height="560" width="560"></canvas>
                            <form method="POST" id="sendImageForm" v-on:Submit="getMnistPredictions" data-url="{% url 'detector:get_mnist_predictions' %}">
                                {% csrf_token %}
                                <input type="hidden" name="canvasImage" id="hiddenInput">
                                <div>
                                    <button type="button" class="btn btn-warning" id="clear-button" v-on:Click="clearClickHandler">
                                        Clear
                                    </button>
                                    <button type="submit" class="btn btn-primary" id="identify">
                                        Get Predictions
                                    </button>
                                </div>

                            </form>

                        </div>
                    </div>
                    <div class="predictions my-3">
                        <div v-for="prediction of data.predictions"
                             v-bind:class="prediction.value == getMaxPrediction ? 'prediction-col top-prediction' : 'prediction-col'"
                             v-bind:id=[['prediction-'+prediction.index.toString()]]>
                            <div class="prediction-bar-container">
                                <div class="prediction-bar" v-bind:style="{height: prediction.value*100 + '%'}"></div>
                            </div>
                            <div class="prediction-number"><strong>[[prediction.index]]</strong></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}

    <!-- development version, includes helpful console warnings -->
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>

    <script src="{% static 'detector/js/mnist_chart.js' %}"></script>

{% endblock %}

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {% block styles %}

    {% endblock %}
</head>
<body>

{% block main_content %}

{% endblock %}

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

{% block scripts %}

{% endblock %}
</body>
</html>